version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - goreleaser --snapshot --clean

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct

  mingo:
    cmds:
      - mise exec go@1.24.1 -- mise install 'go:github.com/bobg/mingo/cmd/mingo@0.13.0'
      - mise exec 'go:github.com/bobg/mingo/cmd/mingo@0.13.0' -- mingo -tests -v
