version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - goreleaser --snapshot --clean

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct
